[package]
name = "cast-codec-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
cast-codec = { path = "../crates/cast-codec" }
libfuzzer-sys = "0.4"

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false
